# Generated by Django 3.1.6 on 2021-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210601_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
