# Generated by Django 3.1.6 on 2021-06-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210602_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
