---
name: Continuous Deployment

on: push

jobs:
  notes-backend-test-action:
    name: Notes Backend Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Backend Test
        run: python3 notes_api/manage.py test

  notes-backend-lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: lint
        run: flake8
