---
name: Continuous Integration

on: push

jobs:
  notes-backend-test-action:
    name: Notes Backend Test
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Backend Test
        with:
          secrets: |
          "SECRET_KEY=${{ secrets.SECRET_KEY }}"
          "DEBUG=${{ secrets.DEBUG }}"
          "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}"
        run: docker-compose run --rm backend sh -c "python3 manage.py test"

  notes-backend-lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: lint
        run: docker-compose run --rm backend sh -c "flake8"
